// End-to-end: two browsers against the real UNDERWAY server. Sign-in, codes, play, "new device" rejoin, finish, replay by code, leaderboard, rematch.
const {Browser,cellXY,waitFor,tapEnemy,showTab,pickWeapon,selectShip,legalMoves,moveShip,setLane,setLine}=require('./cdp.js'); const {spawn}=require('child_process'); const fs=require('fs'); const os=require('os'); const path=require('path');
const PORT=8950+Math.floor(Math.random()*40); const DATA=fs.mkdtempSync(path.join(os.tmpdir(),'underway-e2e-')); const URL='http://127.0.0.1:'+PORT+'/';
const srv=spawn(process.execPath,['--no-warnings=ExperimentalWarning',path.join(__dirname,'..','server','server.js')],{env:Object.assign({},process.env,{PORT:String(PORT),DATA_DIR:DATA}),stdio:['ignore','ignore','pipe']}); srv.stderr.on('data',d=>process.stderr.write('[server] '+d));
process.on('exit',()=>{ try{ srv.kill('SIGKILL'); }catch(e){} try{ fs.rmSync(DATA,{recursive:true,force:true}); }catch(e){} });
const P=(x,y)=>({x,y}); const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function st(b){ return b.eval(`(()=>{const S=Underway.UI.S; const r=S.role; const o=r==='host'?'guest':'host'; return {screen:S.screen, stage:S.game&&S.game.stage, cur:S.game&&S.game.current, phase:S.game&&S.game.phase, turn:S.game&&S.game.turn, busy:S.busy, pending:!!S.pendingFire, link:S.linkState, opp:S.oppOnline, myShots:S.game?S.game.players[r].shots.length:0, theirShots:S.game?S.game.players[o].shots.length:0, winner:S.game&&S.game.winner, role:r, room:S.room};})()`); }
async function signIn(b,name,pin){ await b.goto(URL); await b.wait(500); await b.eval(`document.getElementById('adm-name').value=${JSON.stringify(name)}; document.getElementById('adm-pin').value=${JSON.stringify(pin)};`); await b.click('#btn-signin'); await waitFor(b, `!document.getElementById('online-panel').classList.contains('hidden')`, 8000, 'signed in'); }
async function cellsOf(b,idx){ return b.eval(`(()=>{const S=Underway.UI.S; return Underway.Rules.shipCells(S.game.players[S.role].fleet[${idx}]);})()`); }
async function settleBoth(att,def){ for(let i=0;i<150;i++){ const a=await st(att), d=await st(def); if(!a.busy&&!a.pending&&!d.busy&&a.turn===d.turn&&a.cur===d.cur) return [a,d]; await att.wait(200); if(i%3===2){ await att.eval(`Underway.Anim.skip()`); await def.eval(`Underway.Anim.skip()`); } } throw new Error('did not settle: '+JSON.stringify([await st(att), await st(def)])); }
async function fireShell(att,def,cell){ if((await att.eval(`Underway.UI.S.weapon`))!=='shell') await pickWeapon(att,'shell'); else await showTab(att,'enemy'); await tapEnemy(att,cell); await att.wait(400); await tapEnemy(att,cell); return settleBoth(att,def); } // tap, tap again = fire
(async()=>{
  for(let i=0;i<40;i++){ try{ await fetch(URL+'api/health'); break; }catch(e){ await sleep(150); } }
  const H=new Browser({}), G=new Browser({}); await H.launch(); await G.launch();
  await signIn(H,'Alice','1234'); await H.click('#btn-newgame'); await waitFor(H, `Underway.UI.S.screen==='lobby' && Underway.UI.S.linkState==='online'`, 10000, 'host lobby online'); const code=await H.eval(`Underway.UI.S.room`); console.log('game code', code);
  await signIn(G,'Bob','2222'); await G.click('#btn-join-toggle'); await G.eval(`document.getElementById('join-code').value='${code.toLowerCase()}'`); await G.click('#btn-join'); await waitFor(G, `Underway.UI.S.screen==='lobby' && Underway.UI.S.linkState==='online'`, 10000, 'guest lobby online');
  await waitFor(H, `Underway.UI.S.oppOnline===true && Underway.UI.S.lobby.guestName==='Bob'`, 8000, 'host sees Bob'); console.log('lobby: host sees guest', await H.eval(`Underway.UI.S.lobby.guestName+' online='+Underway.UI.S.oppOnline`), '| guest sees host', await G.eval(`Underway.UI.S.lobby.hostName`));
  await H.click('.navybtn:nth-child(3)'); await G.wait(400); await G.click('#btn-navy-random'); await waitFor(H, `Underway.UI.S.lobby.guestNavy`, 6000, 'guest navy at host'); await H.click('#btn-lobby-start'); await waitFor(G, `Underway.UI.S.screen==='place'`, 8000, 'guest placement');
  await H.click('.tpl[data-tpl="spread"]'); await H.click('#btn-ready'); await G.click('.tpl[data-tpl="cluster"]'); await G.click('#btn-ready');
  await waitFor(H, `Underway.UI.S.screen==='battle'`, 15000, 'host battle'); await waitFor(G, `Underway.UI.S.screen==='battle'`, 15000, 'guest battle');
  for(const b of [H,G]) await b.eval(`Underway.UI.S.settings.fast=true; Underway.Anim.settings.fast=true;`);
  const first=await H.eval(`Underway.UI.S.game.first`); console.log('first', first, 'agree:', first===await G.eval(`Underway.UI.S.game.first`));
  const roles={host:H, guest:G}; let att=roles[first], def=roles[first==='host'?'guest':'host'];
  let [a,d]=await fireShell(att,def,(await cellsOf(def,1))[0]); console.log('shot 1:', a.myShots, d.theirShots, 'turn', a.turn); [att,def]=[def,att];
  // machine gun through the modal
  const bb=await cellsOf(def,0); await pickWeapon(att,'mg',1); for(const c of [bb[0],bb[1],P(9,9),P(0,9)]) await tapEnemy(att,c); await att.click('#tray-fire'); [a,d]=await settleBoth(att,def); console.log('MG:', await att.eval(`JSON.stringify(Underway.UI.S.game.players[Underway.UI.S.role].shots.slice(-4).map(x=>x.result))`), '| def sightings', await def.eval(`Underway.UI.S.game.players[Underway.UI.S.role].sightings.length`)); [att,def]=[def,att];
  // ---- "new device": close the current attacker's browser entirely, open a fresh one (empty localStorage), sign in, join by code ----
  const attRole=(await st(att)).role; const before=await st(att); att.close(); await sleep(400);
  const N=new Browser({}); await N.launch(); await signIn(N, attRole==='host'?'Alice':'Bob', attRole==='host'?'1234':'2222'); await N.click('#btn-join-toggle'); await N.eval(`document.getElementById('join-code').value='${code}'`); await N.click('#btn-join');
  await waitFor(N, `Underway.UI.S.screen==='battle' && Underway.UI.S.linkState==='online'`, 15000, 'rejoined battle from a fresh browser'); await N.eval(`Underway.UI.S.settings.fast=true; Underway.Anim.settings.fast=true;`); await N.wait(400);
  const after=await st(N); console.log('NEW DEVICE rejoin:', JSON.stringify({before:{turn:before.turn,cur:before.cur,my:before.myShots,their:before.theirShots}, after:{turn:after.turn,cur:after.cur,my:after.myShots,their:after.theirShots,role:after.role,room:after.room}}), '| fleet restored:', await N.eval(`Underway.UI.S.game.players[Underway.UI.S.role].fleet.every(s=>s.bow)`));
  roles[attRole]=N; att=N; def=roles[attRole==='host'?'guest':'host'];
  [a,d]=await fireShell(att,def,(await cellsOf(def,2))[0]); console.log('after rejoin shot: turn', a.turn, a.cur, '| def', d.turn, d.cur); [att,def]=[def,att];
  // ---- refresh the other side too (same browser, F5) ----
  const r2=(await st(att)).role; await att.goto(URL+'?g='+code); await waitFor(att, `Underway.UI.S.screen==='battle' && Underway.UI.S.linkState==='online'`, 15000, 'refresh rejoin'); await att.eval(`Underway.UI.S.settings.fast=true; Underway.Anim.settings.fast=true;`); await att.wait(300);
  console.log('REFRESH rejoin ('+r2+'):', JSON.stringify(await st(att)));
  [a,d]=await fireShell(att,def,(await cellsOf(def,3))[0]); console.log('after refresh shot: turn', a.turn, a.cur);
  // ---- the other weapons over the relay: mine (dormant), move onto it (MINE_HIT travels back), radar, torpedo, air strike ----
  [att,def]=[def,att];
  { const od=await cellsOf(def,2); const ods=await def.eval(`(()=>{const S=Underway.UI.S; return S.game.players[S.role].fleet[2];})()`); const dd={N:[0,-1],E:[1,0],S:[0,1],W:[-1,0]}[ods.heading]; const ahead=P(od[0].x+dd[0],od[0].y+dd[1]);
    await pickWeapon(att,'mine'); await tapEnemy(att,ahead); await att.click('#tray-fire'); [a,d]=await settleBoth(att,def); console.log('MINE laid: owner mines', await att.eval(`Underway.UI.S.game.players[Underway.UI.S.role].mines.length`), '| defender log hides the cell:', await def.eval(`![...document.querySelectorAll('#log div')].some(x=>/laid a mine at/.test(x.textContent))`), '| defender result card:', await def.eval(`document.getElementById('result-text').textContent`)); }
  [att,def]=[def,att];
  { await selectShip(att,2); const moved=await moveShip(att,'advance'); await waitFor(def, `Underway.UI.S.game.players[Underway.UI.S.role].shots.some(x=>x.weapon==='mine')`, 15000, 'MINE_HIT received'); [a,d]=await settleBoth(att,def);
    console.log('MINE_HIT: moved', moved, '| owner shots', await def.eval(`JSON.stringify(Underway.UI.S.game.players[Underway.UI.S.role].shots.filter(x=>x.weapon==='mine').map(x=>x.result+':'+x.cls))`), '| mover phase', a.phase);
    await pickWeapon(att,'radar',0); const dc=await cellsOf(def,0); await tapEnemy(att,dc[1]); await att.click('#tray-fire'); await att.wait(1500); [a,d]=await settleBoth(att,def); console.log('RADAR: contacts', await att.eval(`Underway.UI.S.game.log.filter(e=>e.kind==='radar').map(e=>e.count).join(',')`), '| defender sightings', await def.eval(`Underway.UI.S.game.players[Underway.UI.S.role].sightings.map(x=>x.kind).join(',')`)); }
  [att,def]=[def,att];
  { const td=await cellsOf(def,3); await pickWeapon(att,'torpedo'); await tapEnemy(att,P(0,td[0].y)); await setLane(att,0); await att.click('#tray-fire'); [a,d]=await settleBoth(att,def); console.log('TORPEDO:', await att.eval(`JSON.stringify(Underway.UI.S.game.players[Underway.UI.S.role].shots.filter(x=>x.weapon==='torpedo').map(x=>x.result+':'+(x.cls||'')))`), '| defender wakes', await def.eval(`Underway.UI.S.game.players[Underway.UI.S.role].torpedoes.length`)); }
  [att,def]=[def,att];
  { const ok=await att.eval(`(()=>{const S=Underway.UI.S; const c=S.game.players[S.role].fleet[0]; return !c.sunk&&Underway.Rules.hitCount(c)===0;})()`); if(ok){ const obb=await cellsOf(def,4); const obs=await def.eval(`(()=>{const S=Underway.UI.S; return S.game.players[S.role].fleet[4];})()`); const horiz=obs.heading==='E'||obs.heading==='W'; const anchor=obb.slice().sort((p,q)=>p.x-q.x||p.y-q.y)[0]; await pickWeapon(att,'airstrike'); await tapEnemy(att,anchor); await setLine(att,horiz); await att.click('#tray-fire'); [a,d]=await settleBoth(att,def); console.log('AIRSTRIKE:', await att.eval(`JSON.stringify(Underway.UI.S.game.players[Underway.UI.S.role].shots.filter(x=>x.weapon==='airstrike').map(x=>x.result))`)); } else { console.log('AIRSTRIKE skipped: carrier damaged'); [a,d]=await fireShell(att,def,P(9,9)); } }
  [att,def]=[def,att];
  // ---- finish: surrender from the defender; both see game over; server finalizes ----
  await def.click('#btn-surrender'); await def.wait(150); await def.click('#confirm-yes'); await def.wait(800); await def.eval(`Underway.Cine.skip()`); await att.wait(1200); await att.eval(`Underway.Cine.skip()`); await sleep(800);
  console.log('over screens:', await att.eval(`Underway.UI.S.screen+' '+document.getElementById('over-title').textContent`), '|', await def.eval(`Underway.UI.S.screen+' '+document.getElementById('over-title').textContent`));
  const info=await (await fetch(URL+'api/games/'+code)).json(); console.log('server game:', info.status, info.winner, 'replay events:', info.replay&&info.replay.log.length, 'guest moves in replay:', info.replay&&info.replay.log.filter(e=>e.kind==='move'&&e.player==='guest').length, 'host moves:', info.replay&&info.replay.log.filter(e=>e.kind==='move'&&e.player==='host').length);
  // ---- replay by code from a third, signed-out browser ----
  const V=new Browser({}); await V.launch(); await V.goto(URL+'?g='+code); await V.wait(600); await V.eval(`Underway.UI.openFinishedGame('${code}')`); await waitFor(V, `Underway.UI.S.screen==='over'`, 8000, 'viewer over screen'); console.log('viewer:', await V.eval(`document.getElementById('over-title').textContent+' | rematch disabled='+document.getElementById('btn-rematch').disabled`)); await V.click('#btn-replay'); await V.wait(500); console.log('viewer replay events:', await V.eval(`Underway.Replay.events.length`)); await V.eval(`Underway.Replay.seek(4)`); await V.wait(200); await V.shot(__dirname+'/e2e_replay.png');
  await V.goto(URL); await V.wait(400); await V.eval(`Underway.UI.showLeaderboard()`); await waitFor(V, `Underway.UI.S.screen==='board'`, 6000); console.log('leaderboard rows:', await V.eval(`[...document.querySelectorAll('#board-admirals tbody tr')].map(tr=>tr.textContent.replace(/\\s+/g,' ').trim()).join(' || ')`)); await V.shot(__dirname+'/e2e_board.png'); V.close();
  // ---- rematch: host starts, guest auto-joins, loser fires first ----
  const hostB=roles.host, guestB=roles.guest; await hostB.click('#btn-rematch'); await waitFor(hostB, `Underway.UI.S.screen==='lobby' && Underway.UI.S.room!=='${code}'`, 10000, 'host in rematch lobby'); await waitFor(guestB, `Underway.UI.S.screen==='lobby' && Underway.UI.S.room===Underway.UI.S.room && Underway.UI.S.room!=='${code}'`, 12000, 'guest auto-joined rematch');
  const nc=await hostB.eval(`Underway.UI.S.room`); console.log('rematch code:', nc, 'guest room:', await guestB.eval(`Underway.UI.S.room`), 'nextFirst:', await hostB.eval(`Underway.UI.S.lobby.nextFirst`), await guestB.eval(`Underway.UI.S.lobby.nextFirst`));
  await waitFor(hostB, `Underway.UI.S.oppOnline===true`, 8000, 'rematch: host sees guest'); await hostB.click('.navybtn:nth-child(5)'); await guestB.wait(300); await guestB.click('#btn-navy-random'); await waitFor(hostB, `Underway.UI.S.lobby.guestNavy`, 6000); await hostB.click('#btn-lobby-start'); await waitFor(guestB, `Underway.UI.S.screen==='place'`, 8000); await hostB.click('#btn-random-fleet'); await hostB.click('#btn-ready'); await guestB.click('#btn-random-fleet'); await guestB.click('#btn-ready'); await waitFor(hostB, `Underway.UI.S.screen==='battle'`, 15000); await waitFor(guestB, `Underway.UI.S.screen==='battle'`, 15000);
  console.log('rematch first:', await hostB.eval(`Underway.UI.S.game.first`), await guestB.eval(`Underway.UI.S.game.first`), '(expect the loser)');
  const mg=await (await fetch(URL+'api/me?token='+encodeURIComponent(await hostB.eval(`Underway.UI.S.admiral.token`)))).json(); console.log('my games:', mg.games.map(g=>g.code+':'+g.status).join(', '));
  console.log('HOST ERRORS:', hostB.errors.length?hostB.errors:'none'); console.log('GUEST ERRORS:', guestB.errors.length?guestB.errors:'none');
  hostB.close(); guestB.close(); setTimeout(()=>process.exit(0),300);
})().catch(e=>{ console.error('HARNESS', e); process.exit(1); });
